### PR TITLE
migrate needs to be run with a --noinput option.

### PR DESCRIPTION
**Pull request by smn**
Otherwise it can and will ask for user input and break stuff.

### CODE REVIEW

**Comment by smn** [comment]
@JayH5 ready for review

**Comment by JayH5** [comment]
:+1: huh.. I guess we haven't actually done an migrations before.

**Comment by smn** [comment]
Thanks, how do we get this latest version on docker hub?

**Comment by smn** [comment]
Ah it's done automatically <3

**Pull request merged**
