### PR TITLE
Try the solo pool for the built-in Celery worker

### PR DESCRIPTION
**Pull request by JayH5**

### CODE REVIEW

**Comment by jerith** [comment]
Does this mean `--max-memory-per-child` and `--max-tasks-per-child` (which we should probably be using to control leaked memory) will be ignored? If so, I'm not sure the change will decrease memory usage over the lifetime of a container.

**Comment by JayH5** [comment]
Yes it does.. because there are no child processes. Not sure if/when those flags will be used, though.

**Comment by JayH5** [comment]
The `--max-memory-per-child` option is new in Celery 4, which, as far as I know, we're not using anywhere yet.

**Comment by miltontony** [comment]
I'm personally happy with this - having 1 celery thread is what we've been trying to do to make sure that celery behaves inside a container.

**Comment by jerith** [comment]
There are a bunch of places (although perhaps not in containers) where we use `--max-tasks-per-child` to deal with memory leaks in tasks. Happy to give this a try and see how well it works out for us, though.

**Comment by JayH5** [comment]
This is a very particular and kind of gimped way of running Celery and in general is not the recommended way if the worker is doing any serious work. It's designed for Molo sites, specifically. Seed, for example, doesn't use Celery this way.

**Pull request merged**
